### ISSUE TITLE
Type errors with python 3

### ISSUE THREAD

**Issue by josefahmad** [josefahmad/mongo-shardkey-tools#6]
Sample error:
```
typeerror: split: {"min": {"key": 17273}, "max": {"key": 17332}, "splits": 3, "discards": 0}, chunk: {"min": {"key": null}, "max": {"key": 40}}
'<' not supported between instances of 'NoneType' and 'int'
```

**Comment by josefahmad** [comment]
Thrown in find_split(). Reproduces in python 3 when a chunk boundary value is of type `null`. Does not reproduce in python 2.

```
{ "min" : { "key" : { "$minKey" : 1 } }, "max" : { "key" : null } }
{ "min" : { "key" : null }, "max" : { "key" : 40 } }
```

**Comment by josefahmad** [comment]
Additional TypeError:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "plot_split_distribution.py", line 85, in onclick
    for i in range(min_range - 1, max_range):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by josefahmad** [comment]
Another truth table for the comparison with NoneType (sigh).

**Comment by josefahmad** [comment]
Pull request merged, issue resolved.
